// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9U4vs2iZTp0khZ_xEUuISqjAv4G_jXNo',
    appId: '1:246138112068:android:f40ef80a050d13e6c91411',
    messagingSenderId: '246138112068',
    projectId: 'homepay-2022',
    storageBucket: 'homepay-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_3NoP1PgB-XkSMnoXR8k1h-4li5v0TU',
    appId: '1:246138112068:ios:916bf45f79b5f369c91411',
    messagingSenderId: '246138112068',
    projectId: 'homepay-2022',
    storageBucket: 'homepay-2022.appspot.com',
    iosClientId: '246138112068-emr16l57k7b04v9efj4hkh8eojb85r6b.apps.googleusercontent.com',
    iosBundleId: 'com.homepay.app',
  );
}
